import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitepress";
import type { DefaultTheme } from "vitepress";
import { answerColumn, checkedExamples, defaultColumns, namedOverloads, pageFacts } from "./checks";
import { sheetGroups } from "./sheets";
import { codeDark, codeLight } from "./syntax";

const version = (
  JSON.parse(readFileSync(new URL("../../package.json", import.meta.url), "utf8")) as {
    version: string;
  }
).version;
const repo = "https://github.com/gabreusi/hyrax";

const entryLabel = (text: string, entry?: string) =>
  entry
    ? `<span class="hx-group">${text}</span><code class="hx-group-entry">${entry}</code>`
    : text;

// The API pages and their sidebar are generated by TypeDoc (`npm run docs:api`) before the build.
// The sidebar is reshaped here: entrypoints as headings, the kinds you look up most left open.
const sidebarFile = new URL("../api/typedoc-sidebar.json", import.meta.url);
const OPEN_KINDS = new Set(["Classes", "Functions", "Variables"]);
const MODULE_NAMES: Record<string, string> = {
  "@gabreusi/hyrax": "Core",
  "@gabreusi/hyrax/dom": "Browser",
  "@gabreusi/hyrax/react": "React",
};
function reshape(items: DefaultTheme.SidebarItem[], depth = 0): DefaultTheme.SidebarItem[] {
  return items.map((item) => ({
    ...item,
    text:
      depth === 0 && item.text && MODULE_NAMES[item.text]
        ? entryLabel(MODULE_NAMES[item.text]!, item.text)
        : item.text,
    link: item.link?.replace(/\.md$/, ""),
    collapsed:
      depth === 0
        ? false
        : item.collapsed === undefined
          ? undefined
          : !OPEN_KINDS.has(item.text ?? ""),
    items: item.items && reshape(item.items, depth + 1),
  }));
}
const apiSidebar: DefaultTheme.SidebarItem[] = existsSync(sidebarFile)
  ? reshape(JSON.parse(readFileSync(sidebarFile, "utf8")) as DefaultTheme.SidebarItem[])
  : [];

const guideSidebar: DefaultTheme.SidebarItem[] = [
  ...sheetGroups.map((group) => ({
    text: entryLabel(group.text, group.entry),
    items: group.items.map((sheet) => ({ text: sheet.title, link: sheet.link })),
  })),
  { text: "Reference", items: [{ text: "API reference", link: "/api/" }] },
];

export default defineConfig({
  title: "Hyrax",
  titleTemplate: ":title · Hyrax",
  description:
    "Hyrax is a small TypeScript toolkit with checked examples: range math, case conversion, a seeded random generator you can replay, and DOM and React plumbing.",
  lang: "en",
  // The site lives at https://gabreusi.github.io/hyrax/
  base: "/hyrax/",
  cleanUrls: true,
  lastUpdated: true,
  // Dark first: the docs are read next to an editor. Readers can still switch, and the choice sticks.
  appearance: "dark",
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/hyrax/mark.svg" }],
    ["meta", { name: "theme-color", content: "#0d0c0b" }],
    ["link", { rel: "preconnect", href: "https://fonts.googleapis.com" }],
    ["link", { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" }],
    [
      "link",
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Geist:wght@400..700&family=Geist+Mono:wght@400..600&display=swap",
      },
    ],
  ],
  // The API pages are generated: they have no source file to edit on GitHub.
  transformPageData(pageData) {
    if (pageData.relativePath.startsWith("api/")) pageData.frontmatter.editLink = false;
  },
  markdown: {
    theme: { light: codeLight, dark: codeDark },
    config: (md) => md.use(checkedExamples).use(namedOverloads).use(defaultColumns).use(pageFacts),
    codeTransformers: [answerColumn],
  },
  vite: {
    resolve: {
      // The home page runs the real Random from the source, not a copy.
      alias: { "@hyrax-source": fileURLToPath(new URL("../../src/index.ts", import.meta.url)) },
    },
  },
  themeConfig: {
    logo: { src: "/mark.svg", alt: "" },
    siteTitle: "Hyrax",
    nav: [
      { text: "Guide", link: "/guide/getting-started", activeMatch: "^/guide/" },
      { text: "API", link: "/api/", activeMatch: "^/api/" },
      { text: "Design notes", link: "/notes/design", activeMatch: "^/notes/" },
      {
        text: version,
        items: [
          { text: "Changelog", link: `${repo}/blob/main/CHANGELOG.md` },
          { text: "Migrating from 0.x", link: "/migration" },
          { text: "0.x source (legacy-0.6.1)", link: `${repo}/tree/legacy-0.6.1` },
        ],
      },
    ],
    sidebar: {
      "/guide/": guideSidebar,
      "/notes/": guideSidebar,
      "/migration": guideSidebar,
      "/api/": [
        { text: "API reference", items: [{ text: "Overview", link: "/api/" }] },
        ...apiSidebar,
      ],
    },
    outline: { level: [2, 3], label: "On this page" },
    docFooter: { prev: "Previous page", next: "Next page" },
    lastUpdated: { text: "Updated", formatOptions: { dateStyle: "medium" } },
    search: {
      provider: "local",
      options: {
        translations: {
          button: { buttonText: "Search", buttonAriaLabel: "Search the docs" },
          modal: { noResultsText: "No results for" },
        },
      },
    },
    socialLinks: [{ icon: "github", link: repo }],
    editLink: {
      pattern: `${repo}/edit/main/site/:path`,
      text: "Edit this page on GitHub",
    },
    footer: {
      message:
        "MIT License. Every example on these pages is type-checked against the built package, and the core ones are run.",
      copyright: "© 2026 Gabriel Pantano Signorini",
    },
    returnToTopLabel: "Back to top",
    sidebarMenuLabel: "Contents",
  },
});
