import { existsSync, readFileSync } from "node:fs";
import { defineConfig } from "vitepress";
import type { DefaultTheme } from "vitepress";

// The API pages and their sidebar are generated by TypeDoc (`npm run docs:api`) before the build.
const sidebarFile = new URL("../api/typedoc-sidebar.json", import.meta.url);
const apiSidebar: DefaultTheme.SidebarItem[] = existsSync(sidebarFile)
  ? (JSON.parse(readFileSync(sidebarFile, "utf8")) as DefaultTheme.SidebarItem[])
  : [];

export default defineConfig({
  title: "Hyrax",
  description:
    "A small TypeScript toolkit: seeded random, number and string helpers, and DOM and React utilities.",
  // The site lives at https://gabreusi.github.io/hyrax/
  base: "/hyrax/",
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/getting-started" },
      { text: "API", link: "/api/" },
      { text: "Design notes", link: "/notes/design" },
      { text: "Migration", link: "/migration" },
    ],
    sidebar: {
      "/guide/": [
        {
          text: "Guide",
          items: [
            { text: "Getting started", link: "/guide/getting-started" },
            { text: "Numbers", link: "/guide/numbers" },
            { text: "Strings", link: "/guide/strings" },
            { text: "Random", link: "/guide/random" },
            { text: "Everyday helpers", link: "/guide/functions" },
            { text: "Suspend", link: "/guide/suspend" },
            { text: "DOM utilities", link: "/guide/dom" },
            { text: "React", link: "/guide/react" },
          ],
        },
      ],
      "/api/": apiSidebar,
    },
    search: { provider: "local" },
    socialLinks: [{ icon: "github", link: "https://github.com/gabreusi/hyrax" }],
    editLink: {
      pattern: "https://github.com/gabreusi/hyrax/edit/main/site/:path",
      text: "Edit this page on GitHub",
    },
    footer: {
      message: "Released under the MIT License.",
      copyright: "Copyright © Gabriel Pantano Signorini",
    },
  },
});
